config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password

  before_validation :ensure_session_token

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user
    user.is_password?(password) ? user : nil
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])

  end

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def index
  end

  def destroy
  end

  def show
  end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      render :new
    end 

  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.new(user_params)
    if user.save
      login(user)
      redirect_to user_url(user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bands/index.html.erb
<h1>Here's all teh bandz:</h1>
<ul>
<% Band.each. do |band| %>
  <li> <a href="<%= band_url(band) %>"><p><%= Band.name %> </p></a></li>
<% end  %>

app/views/bands/new.html.erb
<h1>Make a band! Poof!</h1>

<form class="" action="<%= band_url %>" method="post">
  <label> Create a band: <input type="text" name="band[:name]" value=""></label> 
</form>

app/views/bands/show.html.erb
<h1>Here's an Extra Special Band for You!</h1>
<%  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header>
      Music App

        <form action="<%= session_url %>" method="post">
          <!-- <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"> -->
          <input type="hidden" name="_method" value="delete">
          <input type="submit" value="Logout">
      </form>

    </header>
    <div class="solid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<div class="solid">
<form action= "<%=action_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Email:
    <input type="text" name="user[email]" value=""> </label>
  <br><br>

  <label>Password:
    <input type="text" name="user[password]" value=""> </label><br><br>

  <input type="submit" value="Log in!"></input>


</form>
</div>

app/views/users/new.html.erb
<h1>Want to join us?</h1><br><br>
<h2>Start a new account!</h2>

<%= render 'form', action_url: users_url %>

<footer> fuck everything </footer>

app/views/users/show.html.erb
<h1>This page belongs to: <%= @user.email %><h1>